package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * BillEntry generated by hbm2java
 */
public class BillEntry implements java.io.Serializable {

  private static final long serialVersionUID = 2295578399737856747L;
  private int billId;
  private int projectId;
  private String categoryCode;
  private String username;
  private Date startTime;
  private Date endTime;
  private Integer billMins;
  private String billable;
  private String billCode;
  private ProjectProvider provider;

  public int getBillId() {
    return this.billId;
  }

  public void setBillId(int billId) {
    this.billId = billId;
  }

  public int getProjectId() {
    return this.projectId;
  }

  public void setProjectId(int projectId) {
    this.projectId = projectId;
  }

  public String getCategoryCode() {
    return this.categoryCode;
  }

  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public Date getStartTime() {
    return this.startTime;
  }

  public void setStartTime(Date startTime) {
    this.startTime = startTime;
  }

  public Date getEndTime() {
    return this.endTime;
  }

  public void setEndTime(Date endTime) {
    this.endTime = endTime;
  }

  public Integer getBillMins() {
    return this.billMins;
  }


  public void setBillMins(Integer billMins) {
    this.billMins = billMins;
  }

  public String getBillable() {
    return this.billable;
  }

  public void setBillable(String billable) {
    this.billable = billable;
  }

  public String getBillCode() {
    return this.billCode;
  }

  public void setBillCode(String billCode) {
    this.billCode = billCode;
  }

  public ProjectProvider getProvider() {
    return provider;
  }

  public void setProvider(ProjectProvider provider) {
    this.provider = provider;
  }

}
