package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * BillExpected generated by hbm2java
 */
public class BillExpected implements java.io.Serializable
{

  private BillExpectedId id;
  private int billMins;
  private int billAmount;
  private String workStatus;

  public BillExpected() {
  }

  public BillExpected(BillExpectedId id, int billMins, int billAmount) {
    this.id = id;
    this.billMins = billMins;
    this.billAmount = billAmount;
  }

  public BillExpected(BillExpectedId id, int billMins, int billAmount, String workStatus) {
    this.id = id;
    this.billMins = billMins;
    this.billAmount = billAmount;
    this.workStatus = workStatus;
  }

  public BillExpectedId getId()
  {
    return this.id;
  }

  public void setId(BillExpectedId id)
  {
    this.id = id;
  }

  public int getBillMins()
  {
    return this.billMins;
  }

  public void setBillMins(int billMins)
  {
    this.billMins = billMins;
  }

  public int getBillAmount()
  {
    return this.billAmount;
  }

  public void setBillAmount(int billAmount)
  {
    this.billAmount = billAmount;
  }

  public String getWorkStatus()
  {
    return this.workStatus;
  }

  public void setWorkStatus(String workStatus)
  {
    this.workStatus = workStatus;
  }

}
