package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * BillWorkStatus generated by hbm2java
 */
public class BillWorkStatus implements java.io.Serializable {

  private String workStatus;
  private String workLabel;

  public BillWorkStatus() {}

  public BillWorkStatus(String workStatus, String workLabel) {
    this.workStatus = workStatus;
    this.workLabel = workLabel;
  }

  public String getWorkStatus() {
    return this.workStatus;
  }

  public void setWorkStatus(String workStatus) {
    this.workStatus = workStatus;
  }

  public String getWorkLabel() {
    return this.workLabel;
  }

  public void setWorkLabel(String workLabel) {
    this.workLabel = workLabel;
  }

}
