package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectContact generated by hbm2java
 */
public class ProjectContact implements java.io.Serializable {

  private static final long serialVersionUID = 4034025707997290581L;
  
  private int contactId;
  private String nameLast;
  private String nameFirst;
  private String nameTitle;
  private String organizationName;
  private String departmentName;
  private String positionTitle;
  private String phoneNumber = "";
  private boolean phoneTextable = false;
  private String emailAddress;
  private boolean emailConfirmed = false;
  private String contactInfo;
  private String emailAlert;
  private ProjectProvider provider = null;
  private String timeZone = "";
  private ProjectAddress address = null;

  public String getName() {
    return nameFirst + " " + nameLast;
  }

  public int getContactId() {
    return this.contactId;
  }

  public void setContactId(int contactId) {
    this.contactId = contactId;
  }

  public String getNameLast() {
    return this.nameLast;
  }

  public void setNameLast(String nameLast) {
    this.nameLast = nameLast;
  }

  public String getNameFirst() {
    return this.nameFirst;
  }

  public void setNameFirst(String nameFirst) {
    this.nameFirst = nameFirst;
  }

  public String getNameTitle() {
    return this.nameTitle;
  }

  public void setNameTitle(String nameTitle) {
    this.nameTitle = nameTitle;
  }

  public String getOrganizationName() {
    return this.organizationName;
  }

  public void setOrganizationName(String organizationName) {
    this.organizationName = organizationName;
  }

  public String getDepartmentName() {
    return this.departmentName;
  }

  public void setDepartmentName(String departmentName) {
    this.departmentName = departmentName;
  }

  public String getPositionTitle() {
    return this.positionTitle;
  }

  public void setPositionTitle(String positionTitle) {
    this.positionTitle = positionTitle;
  }

  public String getPhoneNumber() {
    return this.phoneNumber;
  }

  public void setPhoneNumber(String numberPhone) {
    this.phoneNumber = numberPhone;
  }

  public String getEmailAddress() {
    return this.emailAddress;
  }

  public void setEmailAddress(String email) {
    this.emailAddress = email;
  }

  public String getContactInfo() {
    return this.contactInfo;
  }

  public void setContactInfo(String contactInfo) {
    this.contactInfo = contactInfo;
  }

  public String getEmailAlert() {
    return this.emailAlert;
  }

  public void setEmailAlert(String emailAlert) {
    this.emailAlert = emailAlert;
  }

  public String getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(String timeZone) {
    this.timeZone = timeZone;
  }

  public ProjectProvider getProvider() {
    return provider;
  }

  public void setProvider(ProjectProvider provider) {
    this.provider = provider;
  }

  public boolean isPhoneTextable() {
    return phoneTextable;
  }

  public void setPhoneTextable(boolean phoneTextable) {
    this.phoneTextable = phoneTextable;
  }

  public boolean isEmailConfirmed() {
    return emailConfirmed;
  }

  public void setEmailConfirmed(boolean emailConfirmed) {
    this.emailConfirmed = emailConfirmed;
  }

  public ProjectAddress getAddress() {
    return address;
  }

  public void setAddress(ProjectAddress address) {
    this.address = address;
  }

}
