package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectPhase generated by hbm2java
 */
public class ProjectPhase implements java.io.Serializable
{

  private String phaseCode;
  private String phaseLabel;

  public ProjectPhase() {
  }

  public ProjectPhase(String phaseCode) {
    this.phaseCode = phaseCode;
  }

  public ProjectPhase(String phaseCode, String phaseLabel) {
    this.phaseCode = phaseCode;
    this.phaseLabel = phaseLabel;
  }

  public String getPhaseCode()
  {
    return this.phaseCode;
  }

  public void setPhaseCode(String phaseCode)
  {
    this.phaseCode = phaseCode;
  }

  public String getPhaseLabel()
  {
    return this.phaseLabel;
  }

  public void setPhaseLabel(String phaseLabel)
  {
    this.phaseLabel = phaseLabel;
  }

}
