package org.openimmunizationsoftware.pt.model;

import java.util.List;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

  private static final long serialVersionUID = -5980583072580894435L;
  private int projectId;
  private String categoryCode;
  private String projectName;
  private String providerName;
  private String description;
  private String phaseCode;
  private Integer profileId;
  private String billCode;
  private ProjectProvider provider;
  private String username;
  private ProjectCategory projectCategory = null;
  private ProjectPhase projectPhase = null;
  private int priorityLevel = 0;

  public int getPriorityLevel() {
    return priorityLevel;
  }

  public void setPriorityLevel(int priorityLevel) {
    this.priorityLevel = priorityLevel;
  }

  public ProjectCategory getProjectCategory() {
    return projectCategory;
  }

  public void setProjectCategory(ProjectCategory projectCategory) {
    this.projectCategory = projectCategory;
  }

  public ProjectPhase getProjectPhase() {
    return projectPhase;
  }

  public void setProjectPhase(ProjectPhase projectPhase) {
    this.projectPhase = projectPhase;
  }

  private List<ProjectContactAssigned> projectContactAssignedList = null;

  public List<ProjectContactAssigned> getProjectContactAssignedList() {
    return projectContactAssignedList;
  }

  public boolean isAssigned(ProjectContact projectContact) {
    for (ProjectContactAssigned projectContactAssigned : projectContactAssignedList) {
      if (projectContactAssigned.getProjectContact().getContactId() == projectContact
          .getContactId()) {
        return true;
      }
    }
    return false;
  }

  public void setProjectContactAssignedList(
      List<ProjectContactAssigned> projectContactAssignedList) {
    this.projectContactAssignedList = projectContactAssignedList;
  }

  public int getProjectId() {
    return this.projectId;
  }

  public void setProjectId(int projectId) {
    this.projectId = projectId;
  }

  public String getCategoryCode() {
    return this.categoryCode;
  }

  public void setCategoryCode(String categoryCode) {
    this.categoryCode = categoryCode;
  }

  public String getProjectName() {
    return this.projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public String getProviderName() {
    return this.providerName;
  }

  public void setProviderName(String providerName) {
    this.providerName = providerName;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getPhaseCode() {
    return this.phaseCode;
  }

  public void setPhaseCode(String phaseCode) {
    this.phaseCode = phaseCode;
  }

  public Integer getProfileId() {
    return this.profileId;
  }

  public void setProfileId(Integer profileId) {
    this.profileId = profileId;
  }

  public String getBillCode() {
    return this.billCode;
  }

  public void setBillCode(String billCode) {
    this.billCode = billCode;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public ProjectProvider getProvider() {
    return provider;
  }

  public void setProvider(ProjectProvider provider) {
    this.provider = provider;
  }

}
