package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectProvider generated by hbm2java
 */
public class ProjectProvider implements java.io.Serializable {

  private String providerId;
  private String providerName;

  public ProjectProvider() {}

  public ProjectProvider(String providerId, String providerName) {
    this.providerId = providerId;
    this.providerName = providerName;
  }

  public String getProviderId() {
    return this.providerId;
  }

  public void setProviderId(String providerId) {
    this.providerId = providerId;
  }

  public String getProviderName() {
    return this.providerName;
  }

  public void setProviderName(String providerName) {
    this.providerName = providerName;
  }

}
