package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectAreaAssigned generated by hbm2java
 */
public class ProjectAreaAssigned implements java.io.Serializable
{

  private ProjectAreaAssignedId id;

  public ProjectAreaAssigned() {
  }

  public ProjectAreaAssigned(ProjectAreaAssignedId id) {
    this.id = id;
  }

  public ProjectAreaAssignedId getId()
  {
    return this.id;
  }

  public void setId(ProjectAreaAssignedId id)
  {
    this.id = id;
  }

}
