package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectBookmarkId generated by hbm2java
 */
public class ProjectBookmarkId implements java.io.Serializable
{

  private int projectId;
  private String bookmarkLabel;

  public ProjectBookmarkId() {
  }

  public ProjectBookmarkId(int projectId, String bookmarkLabel) {
    this.projectId = projectId;
    this.bookmarkLabel = bookmarkLabel;
  }

  public int getProjectId()
  {
    return this.projectId;
  }

  public void setProjectId(int projectId)
  {
    this.projectId = projectId;
  }

  public String getBookmarkLabel()
  {
    return this.bookmarkLabel;
  }

  public void setBookmarkLabel(String bookmarkLabel)
  {
    this.bookmarkLabel = bookmarkLabel;
  }

  public boolean equals(Object other)
  {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ProjectBookmarkId))
      return false;
    ProjectBookmarkId castOther = (ProjectBookmarkId) other;

    return (this.getProjectId() == castOther.getProjectId())
        && ((this.getBookmarkLabel() == castOther.getBookmarkLabel()) || (this.getBookmarkLabel() != null && castOther.getBookmarkLabel() != null && this
            .getBookmarkLabel().equals(castOther.getBookmarkLabel())));
  }

  public int hashCode()
  {
    int result = 17;

    result = 37 * result + this.getProjectId();
    result = 37 * result + (getBookmarkLabel() == null ? 0 : this.getBookmarkLabel().hashCode());
    return result;
  }

}
