package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectContactAssigned generated by hbm2java
 */
public class ProjectContactSupervisor implements java.io.Serializable {

  private int contactSupervisorId = 0;
  private ProjectContact contact = null;
  private ProjectContact supervisor = null;
  private String emailAlert = "";

  public String getEmailAlert() {
    return emailAlert;
  }

  public void setEmailAlert(String emailAlert) {
    this.emailAlert = emailAlert;
  }

  public int getContactSupervisorId() {
    return contactSupervisorId;
  }

  public void setContactSupervisorId(int contactSupervisorId) {
    this.contactSupervisorId = contactSupervisorId;
  }

  public ProjectContact getContact() {
    return contact;
  }

  public void setContact(ProjectContact contact) {
    this.contact = contact;
  }

  public ProjectContact getSupervisor() {
    return supervisor;
  }

  public void setSupervisor(ProjectContact supervisor) {
    this.supervisor = supervisor;
  }

}
