package org.openimmunizationsoftware.pt.model;

import java.util.Date;
import java.util.List;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable {

  private static final long serialVersionUID = -5980583072580894435L;
  private int projectId;
  private String projectName;
  private String projectHandle;
  private String description;
  private String outcomeText;
  private String successCriteriaText;
  private String projectStatus;
  private String billCode;
  private String projectIcon;
  private Integer workspaceId;
  private Integer createdByWebUserId;
  private Integer lastModifiedByWebUserId;
  private Integer linkedPatchWorkspaceId;
  private String externalSourceKey;
  private String externalProjectId;
  private boolean externalManaged = false;
  private Date externalLastSyncedAt;
  private WebUser webUser;
  private int priorityLevel = 0;

  public int getPriorityLevel() {
    return priorityLevel;
  }

  public void setPriorityLevel(int priorityLevel) {
    this.priorityLevel = priorityLevel;
  }

  private List<ProjectContactAssigned> projectContactAssignedList = null;

  public List<ProjectContactAssigned> getProjectContactAssignedList() {
    return projectContactAssignedList;
  }

  public boolean isAssigned(ProjectContact projectContact) {
    for (ProjectContactAssigned projectContactAssigned : projectContactAssignedList) {
      if (projectContactAssigned.getProjectContact().getContactId() == projectContact
          .getContactId()) {
        return true;
      }
    }
    return false;
  }

  public void setProjectContactAssignedList(
      List<ProjectContactAssigned> projectContactAssignedList) {
    this.projectContactAssignedList = projectContactAssignedList;
  }

  public int getProjectId() {
    return this.projectId;
  }

  public void setProjectId(int projectId) {
    this.projectId = projectId;
  }

  public String getProjectName() {
    return this.projectName;
  }

  public void setProjectName(String projectName) {
    this.projectName = projectName;
  }

  public String getProjectHandle() {
    return projectHandle;
  }

  public void setProjectHandle(String projectHandle) {
    this.projectHandle = projectHandle;
  }

  public String getDescription() {
    return this.description;
  }

  public void setDescription(String description) {
    this.description = description;
  }

  public String getOutcomeText() {
    return this.outcomeText;
  }

  public void setOutcomeText(String outcomeText) {
    this.outcomeText = outcomeText;
  }

  public String getSuccessCriteriaText() {
    return this.successCriteriaText;
  }

  public void setSuccessCriteriaText(String successCriteriaText) {
    this.successCriteriaText = successCriteriaText;
  }

  public String getProjectStatus() {
    return projectStatus;
  }

  public void setProjectStatus(String projectStatus) {
    this.projectStatus = projectStatus;
  }

  public ProjectStatus getProjectStatusEnum() {
    return ProjectStatus.fromDatabaseValue(projectStatus);
  }

  public void setProjectStatusEnum(ProjectStatus projectStatusEnum) {
    this.projectStatus = projectStatusEnum == null ? null : projectStatusEnum.getDatabaseValue();
  }

  public String getBillCode() {
    return this.billCode;
  }

  public void setBillCode(String billCode) {
    this.billCode = billCode;
  }

  public String getProjectIcon() {
    return this.projectIcon;
  }

  public void setProjectIcon(String projectIcon) {
    this.projectIcon = projectIcon;
  }

  public Integer getWorkspaceId() {
    return workspaceId;
  }

  public void setWorkspaceId(Integer workspaceId) {
    this.workspaceId = workspaceId;
  }

  public Integer getLinkedPatchWorkspaceId() {
    return linkedPatchWorkspaceId;
  }

  public void setLinkedPatchWorkspaceId(Integer linkedPatchWorkspaceId) {
    this.linkedPatchWorkspaceId = linkedPatchWorkspaceId;
  }

  public Integer getCreatedByWebUserId() {
    return createdByWebUserId;
  }

  public void setCreatedByWebUserId(Integer createdByWebUserId) {
    this.createdByWebUserId = createdByWebUserId;
  }

  public Integer getLastModifiedByWebUserId() {
    return lastModifiedByWebUserId;
  }

  public void setLastModifiedByWebUserId(Integer lastModifiedByWebUserId) {
    this.lastModifiedByWebUserId = lastModifiedByWebUserId;
  }

  public String getExternalSourceKey() {
    return externalSourceKey;
  }

  public void setExternalSourceKey(String externalSourceKey) {
    this.externalSourceKey = externalSourceKey;
  }

  public String getExternalProjectId() {
    return externalProjectId;
  }

  public void setExternalProjectId(String externalProjectId) {
    this.externalProjectId = externalProjectId;
  }

  public boolean isExternalManaged() {
    return externalManaged;
  }

  public void setExternalManaged(boolean externalManaged) {
    this.externalManaged = externalManaged;
  }

  public Date getExternalLastSyncedAt() {
    return externalLastSyncedAt;
  }

  public void setExternalLastSyncedAt(Date externalLastSyncedAt) {
    this.externalLastSyncedAt = externalLastSyncedAt;
  }

  public String getUsername() {
    return webUser != null ? webUser.getUsername() : null;
  }

  public void setUsername(String username) {
    // no-op: use setWebUser() instead
  }

  public WebUser getWebUser() {
    return webUser;
  }

  public void setWebUser(WebUser webUser) {
    this.webUser = webUser;
  }

}
