package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ProjectAction generated by hbm2java
 */
public class ProjectAction implements java.io.Serializable
{

  private int actionId;
  private int projectId;
  private int contactId;
  private Date actionDate;
  private String actionDescription;
  private String nextDescription;
  private Date nextDue;
  private String nextActionType;
  private Integer nextTimeEstimate;
  private Integer nextContactId;
  private Integer nextActionId;
  private String providerId;
  private ProjectContact nextProjectContact = null;
  private Project project = null;
  

  public Project getProject()
  {
    return project;
  }

  public void setProject(Project project)
  {
    this.project = project;
  }

  public ProjectContact getNextProjectContact()
  {
    return nextProjectContact;
  }

  public void setNextProjectContact(ProjectContact nextProjectContact)
  {
    this.nextProjectContact = nextProjectContact;
  }

  public ProjectAction() {
  }

  public ProjectAction(int actionId, int projectId, int contactId, Date actionDate, String providerId) {
    this.actionId = actionId;
    this.projectId = projectId;
    this.contactId = contactId;
    this.actionDate = actionDate;
    this.providerId = providerId;
  }

  public ProjectAction(int actionId, int projectId, int contactId, Date actionDate, String actionDescription, String nextDescription, Date nextDue,
      String nextActionType, Integer nextTimeEstimate, Integer nextContactId, Integer nextActionId, String providerId) {
    this.actionId = actionId;
    this.projectId = projectId;
    this.contactId = contactId;
    this.actionDate = actionDate;
    this.actionDescription = actionDescription;
    this.nextDescription = nextDescription;
    this.nextDue = nextDue;
    this.nextActionType = nextActionType;
    this.nextTimeEstimate = nextTimeEstimate;
    this.nextContactId = nextContactId;
    this.nextActionId = nextActionId;
    this.providerId = providerId;
  }

  public int getActionId()
  {
    return this.actionId;
  }

  public void setActionId(int actionId)
  {
    this.actionId = actionId;
  }

  public int getProjectId()
  {
    return this.projectId;
  }

  public void setProjectId(int projectId)
  {
    this.projectId = projectId;
  }

  public int getContactId()
  {
    return this.contactId;
  }

  public void setContactId(int contactId)
  {
    this.contactId = contactId;
  }

  public Date getActionDate()
  {
    return this.actionDate;
  }

  public void setActionDate(Date actionDate)
  {
    this.actionDate = actionDate;
  }

  public String getActionDescription()
  {
    return this.actionDescription;
  }

  public void setActionDescription(String actionDescription)
  {
    this.actionDescription = actionDescription;
  }

  public String getNextDescription()
  {
    return this.nextDescription;
  }
  
  public String getNextDescriptionForDisplay()
  {
    String description = "";
    String type = getNextActionType();
    if (type == null || type.equals(""))
    {
      description = getNextDescription();
    } else if (type.equals("A"))
    {
      if (nextProjectContact == null)
      {
        description = "<i>I am asking for</i> " + getNextDescription();
      } else
      {
        description = "<i>I am asking " + nextProjectContact.getName() + " to</i> " + getNextDescription();
      }
    } else if (type.equals("C"))
    {
      if (nextProjectContact == null)
      {
        description = "<i>I will make contact about</i> " + getNextDescription();
      } else
      {
        description = "<i>I will contact " + nextProjectContact.getName() + " about</i> " + getNextDescription();
      }
    } else if (type.equals("D"))
    {
      description = "<i>I will</i> " + getNextDescription();
    } else if (type.equals("E"))
    {
      description = "<i>I will run errand to</i>" + getNextDescription();
    } else if (type.equals("G"))
    {
      if (nextProjectContact == null)
      {
        description = "<i>I have set a goal to </i> " + getNextDescription();
      } else
      {
        description = "<i>I have set a goal with " + nextProjectContact.getName() + " to</i> " + getNextDescription();
      }
    } else if (type.equals("M"))
    {
      description = "<i>I might</i> " + getNextDescription();
    } else if (type.equals("T"))
    {
      if (nextProjectContact == null)
      {
        description = "<i>I have committed to </i> " + getNextDescription();
      } else
      {
        description = "<i>I have committed to " + nextProjectContact.getName() + " to</i> " + getNextDescription();
      }
    } else if (type.equals("W"))
    {
      if (nextProjectContact == null)
      {
        description = "<i>I am waiting for </i> " + getNextDescription();
      } else
      {
        description = "<i>I am waiting for " + nextProjectContact.getName() + " to</i> " + getNextDescription();
      }
    }
    return description;
  }

  public void setNextDescription(String nextDescription)
  {
    this.nextDescription = nextDescription;
  }

  public Date getNextDue()
  {
    return this.nextDue;
  }

  public void setNextDue(Date nextDue)
  {
    this.nextDue = nextDue;
  }

  public String getNextActionType()
  {
    return this.nextActionType;
  }

  public void setNextActionType(String nextActionType)
  {
    this.nextActionType = nextActionType;
  }

  public Integer getNextTimeEstimate()
  {
    return this.nextTimeEstimate;
  }

  public void setNextTimeEstimate(Integer nextTimeEstimate)
  {
    this.nextTimeEstimate = nextTimeEstimate;
  }

  public Integer getNextContactId()
  {
    return this.nextContactId;
  }

  public void setNextContactId(Integer nextContactId)
  {
    this.nextContactId = nextContactId;
  }

  public Integer getNextActionId()
  {
    return this.nextActionId;
  }

  public void setNextActionId(Integer nextActionId)
  {
    this.nextActionId = nextActionId;
  }

  public String getProviderId()
  {
    return this.providerId;
  }

  public void setProviderId(String providerId)
  {
    this.providerId = providerId;
  }

}
