package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectClientId generated by hbm2java
 */
public class ProjectClientId implements java.io.Serializable {

  private String clientCode;
  private String providerId;

  public ProjectClientId() {}

  public ProjectClientId(String clientCode, String providerId) {
    this.clientCode = clientCode;
    this.providerId = providerId;
  }

  public String getClientCode() {
    return this.clientCode;
  }

  public void setClientCode(String clientCode) {
    this.clientCode = clientCode;
  }

  public String getProviderId() {
    return this.providerId;
  }

  public void setProviderId(String providerId) {
    this.providerId = providerId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof ProjectClientId))
      return false;
    ProjectClientId castOther = (ProjectClientId) other;

    return ((this.getClientCode() == castOther.getClientCode())
        || (this.getClientCode() != null && castOther.getClientCode() != null
            && this.getClientCode().equals(castOther.getClientCode())))
        && ((this.getProviderId() == castOther.getProviderId())
            || (this.getProviderId() != null && castOther.getProviderId() != null
                && this.getProviderId().equals(castOther.getProviderId())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getClientCode() == null ? 0 : this.getClientCode().hashCode());
    result = 37 * result + (getProviderId() == null ? 0 : this.getProviderId().hashCode());
    return result;
  }

}
