package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ProjectNextActionType generated by hbm2java
 */
public class ProjectNextActionType implements java.io.Serializable {

  public static String WILL = "WILL";
  public static String WILL_CONTACT = "WILL_CONTACT";
  public static String WILL_MEET = "WILL_MEET";
  public static String WILL_REVIEW = "REVIEW"; 
  public static String WILL_DOCUMENT = "DOCUMENT"; 
  public static String WILL_FOLLOW_UP = "WILL_FOLLOW_UP";
  public static String MIGHT = "MIGHT";
  public static String COMMITTED_TO = "COMMITTED_TO";
  public static String GOAL = "GOAL";
  public static String WAITING = "WAITING";
  public static String OVERDUE_TO = "OVERDUE_TO"; 

  public static String getLabel(String projectNextActionType) {
    if (projectNextActionType.equals(WILL)) {
      return "Will";
    } else if (projectNextActionType.equals(WILL_CONTACT)) {
      return "Will Contact";
    } else if (projectNextActionType.equals(WILL_MEET)) {
      return "Will Meet";
    } else if (projectNextActionType.equals(WILL_REVIEW)) {
      return "Will Review";
    } else if (projectNextActionType.equals(WILL_DOCUMENT)) {
      return "Will Document";
    } else if (projectNextActionType.equals(WILL_FOLLOW_UP)) {
      return "Follow Up";
    } else if (projectNextActionType.equals(MIGHT)) {
      return "Might";
    } else if (projectNextActionType.equals(COMMITTED_TO)) {
      return "Committed To";
    } else if (projectNextActionType.equals(GOAL)) {
      return "Goal";
    } else if (projectNextActionType.equals(WAITING)) {
      return "Waiting";
    } else if (projectNextActionType.equals(OVERDUE_TO)) {
      return "Overdue";
    }
    return projectNextActionType;
  }
  
  public static int defaultPriority(String projectNextActionType)
  {
    if (projectNextActionType.equals(WILL)) {
      return 3;
    } else if (projectNextActionType.equals(WILL_CONTACT)) {
      return 3;
    } else if (projectNextActionType.equals(WILL_MEET)) {
      return 3;
    } else if (projectNextActionType.equals(WILL_REVIEW)) {
      return 3;
    } else if (projectNextActionType.equals(WILL_DOCUMENT)) {
      return 3;
    } else if (projectNextActionType.equals(WILL_FOLLOW_UP)) {
      return 3;
    } else if (projectNextActionType.equals(MIGHT)) {
      return 2;
    } else if (projectNextActionType.equals(COMMITTED_TO)) {
      return 4;
    } else if (projectNextActionType.equals(GOAL)) {
      return 1;
    } else if (projectNextActionType.equals(WAITING)) {
      return 1;
    } else if (projectNextActionType.equals(OVERDUE_TO)) {
      return 5;
    }
    return 0;
  }
  

  private String nextActionType;
  private String nextActionLabel;

  public ProjectNextActionType() {
  }

  public ProjectNextActionType(String nextActionType, String nextActionLabel) {
    this.nextActionType = nextActionType;
    this.nextActionLabel = nextActionLabel;
  }

  public String getNextActionType() {
    return this.nextActionType;
  }

  public void setNextActionType(String nextActionType) {
    this.nextActionType = nextActionType;
  }

  public String getNextActionLabel() {
    return this.nextActionLabel;
  }

  public void setNextActionLabel(String nextActionLabel) {
    this.nextActionLabel = nextActionLabel;
  }

}
