package org.openimmunizationsoftware.pt.model;

import java.util.List;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * Project generated by hbm2java
 */
public class Project implements java.io.Serializable
{

  private int projectId;
  private String clientCode;
  private String projectName;
  private String providerName;
  private String vendorName;
  private String systemName;
  private String description;
  private String phaseCode;
  private Integer profileId;
  private String billCode;
  private String fileLocation;
  private String providerId;
  private String username;
  private String iisSubmissionCode;
  private String iisFacilityId;
  private String medicalOrganization;
  private ProjectClient projectClient = null;
  private ProjectPhase projectPhase = null;
  private String iisRegionCode;
  
  public String getIisRegionCode()
  {
    return iisRegionCode;
  }

  public void setIisRegionCode(String iisRegionCode)
  {
    this.iisRegionCode = iisRegionCode;
  }

  public String getIisFacilityId()
  {
    return iisFacilityId;
  }

  public void setIisFacilityId(String iisFacilityId)
  {
    this.iisFacilityId = iisFacilityId;
  }

  public String getMedicalOrganization()
  {
    return medicalOrganization;
  }

  public void setMedicalOrganization(String medicalOrganization)
  {
    this.medicalOrganization = medicalOrganization;
  }

  public ProjectClient getProjectClient()
  {
    return projectClient;
  }

  public void setProjectClient(ProjectClient projectClient)
  {
    this.projectClient = projectClient;
  }

  public ProjectPhase getProjectPhase()
  {
    return projectPhase;
  }

  public void setProjectPhase(ProjectPhase projectPhase)
  {
    this.projectPhase = projectPhase;
  }

  public String getIisSubmissionCode()
  {
    return iisSubmissionCode;
  }

  public void setIisSubmissionCode(String iisSubmissionCode)
  {
    this.iisSubmissionCode = iisSubmissionCode;
  }

  private List<ProjectContactAssigned> projectContactAssignedList = null;

  public List<ProjectContactAssigned> getProjectContactAssignedList()
  {
    return projectContactAssignedList;
  }
  
  public boolean isAssigned(ProjectContact projectContact)
  {
    for (ProjectContactAssigned projectContactAssigned: projectContactAssignedList)
    {
      if (projectContactAssigned.getProjectContact().getContactId() == projectContact.getContactId())
      {
        return true;
      }
    }
    return false;
  }

  public void setProjectContactAssignedList(List<ProjectContactAssigned> projectContactAssignedList)
  {
    this.projectContactAssignedList = projectContactAssignedList;
  }

  public Project() {
  }

  public Project(int projectId, String projectName, String username) {
    this.projectId = projectId;
    this.projectName = projectName;
    this.username = username;
  }

  public Project(int projectId, String clientCode, String projectName, String providerName, String vendorName, String systemName, String description,
      String phaseCode, Integer profileId, String billCode, String fileLocation, String providerId, String username) {
    this.projectId = projectId;
    this.clientCode = clientCode;
    this.projectName = projectName;
    this.providerName = providerName;
    this.vendorName = vendorName;
    this.systemName = systemName;
    this.description = description;
    this.phaseCode = phaseCode;
    this.profileId = profileId;
    this.billCode = billCode;
    this.fileLocation = fileLocation;
    this.providerId = providerId;
    this.username = username;
  }

  public int getProjectId()
  {
    return this.projectId;
  }

  public void setProjectId(int projectId)
  {
    this.projectId = projectId;
  }

  public String getClientCode()
  {
    return this.clientCode;
  }

  public void setClientCode(String clientCode)
  {
    this.clientCode = clientCode;
  }

  public String getProjectName()
  {
    return this.projectName;
  }

  public void setProjectName(String projectName)
  {
    this.projectName = projectName;
  }

  public String getProviderName()
  {
    return this.providerName;
  }

  public void setProviderName(String providerName)
  {
    this.providerName = providerName;
  }

  public String getVendorName()
  {
    return this.vendorName;
  }

  public void setVendorName(String vendorName)
  {
    this.vendorName = vendorName;
  }

  public String getSystemName()
  {
    return this.systemName;
  }

  public void setSystemName(String systemName)
  {
    this.systemName = systemName;
  }

  public String getDescription()
  {
    return this.description;
  }

  public void setDescription(String description)
  {
    this.description = description;
  }

  public String getPhaseCode()
  {
    return this.phaseCode;
  }

  public void setPhaseCode(String phaseCode)
  {
    this.phaseCode = phaseCode;
  }

  public Integer getProfileId()
  {
    return this.profileId;
  }

  public void setProfileId(Integer profileId)
  {
    this.profileId = profileId;
  }

  public String getBillCode()
  {
    return this.billCode;
  }

  public void setBillCode(String billCode)
  {
    this.billCode = billCode;
  }

  public String getFileLocation()
  {
    return this.fileLocation;
  }

  public void setFileLocation(String fileLocation)
  {
    this.fileLocation = fileLocation;
  }

  public String getProviderId()
  {
    return this.providerId;
  }

  public void setProviderId(String providerId)
  {
    this.providerId = providerId;
  }

  public String getUsername()
  {
    return this.username;
  }

  public void setUsername(String username)
  {
    this.username = username;
  }

}
