package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * ProjectAction generated by hbm2java
 */
@SuppressWarnings("serial")
public class ProjectAction implements java.io.Serializable {

  private int actionId;
  private int projectId;
  private int contactId;
  private Date actionDate;
  private String actionDescription;
  private String nextDescription;
  private Date nextDue;
  private Date nextDeadline;
  private String nextActionType;
  private Integer nextTimeEstimate;
  private Integer nextTimeActual;
  private Integer nextContactId;
  private Integer nextActionId;
  private ProjectProvider provider;
  private ProjectContact nextProjectContact = null;
  private ProjectContact contact = null;
  private Project project = null;
  private int priorityLevel = 0;
  private String taskStatus;
  private int goalActionId;
  private String linkUrl = "";
  private String nextNotes = "";

  public String getNextNotes() {
    return nextNotes;
  }

  public void setNextNotes(String nextNotes) {
    this.nextNotes = nextNotes;
  }

  public Integer getNextTimeActual() {
    return nextTimeActual;
  }

  public void setNextTimeActual(Integer nextTimeActual) {
    this.nextTimeActual = nextTimeActual;
  }

  public String getLinkUrl() {
    return linkUrl;
  }

  public void setLinkUrl(String linkUrl) {
    this.linkUrl = linkUrl;
  }

  public ProjectContact getContact() {
    return contact;
  }

  public void setContact(ProjectContact contact) {
    this.contact = contact;
  }

  public int getPriorityLevel() {
    return priorityLevel;
  }

  public void setPriorityLevel(int priorityLevel) {
    this.priorityLevel = priorityLevel;
  }

  public Project getProject() {
    return project;
  }

  public void setProject(Project project) {
    this.project = project;
  }

  public ProjectContact getNextProjectContact() {
    return nextProjectContact;
  }

  public void setNextProjectContact(ProjectContact nextProjectContact) {
    this.nextProjectContact = nextProjectContact;
  }

  public int getActionId() {
    return this.actionId;
  }

  public void setActionId(int actionId) {
    this.actionId = actionId;
  }

  public int getProjectId() {
    return this.projectId;
  }

  public void setProjectId(int projectId) {
    this.projectId = projectId;
  }

  public int getContactId() {
    return this.contactId;
  }

  public void setContactId(int contactId) {
    this.contactId = contactId;
  }

  public Date getActionDate() {
    return this.actionDate;
  }

  public void setActionDate(Date actionDate) {
    this.actionDate = actionDate;
  }

  public String getActionDescription() {
    return this.actionDescription;
  }

  public void setActionDescription(String actionDescription) {
    this.actionDescription = actionDescription;
  }

  public String getNextDescription() {
    return this.nextDescription;
  }

  public String getNextDescriptionForDisplay(ProjectContact forContact) {
    String i_am = "I am ";
    String i_ = "I ";
    String i_have = "I have";
    if (forContact == null || forContact.getContactId() != contact.getContactId()) {
      i_am = contact.getName() + " is ";
      i_ = contact.getName() + " ";
      i_have = contact.getName() + " has ";
    }

    String description = "";
    String type = getNextActionType();
    if (type == null || type.equals("")) {
      description = getNextDescription();
    } else if (type.equals(ProjectNextActionType.ASKS_TO)) {
      if (nextProjectContact == null) {
        description = "<i>" + i_am + "asking for ..</i> " + getNextDescription();
      } else {
        description = "<i>" + i_am + "asking " + nextProjectContact.getName() + " to</i> "
            + getNextDescription();
      }
    } else if (type.equals(ProjectNextActionType.WILL_CONTACT)) {
      if (nextProjectContact == null) {
        description = "<i>" + i_ + " will make contact about</i> " + getNextDescription();
      } else {
        description = "<i>" + i_ + " will contact " + nextProjectContact.getName() + " about</i> "
            + getNextDescription();
      }
    } else if (type.equals(ProjectNextActionType.WILL)) {
      description = "<i>" + i_ + " will</i> " + getNextDescription();
    } else if (type.equals(ProjectNextActionType.WILL_MEET)) {
      description = "<i>" + i_ + " will meet</i> " + getNextDescription();
    } else if (type.equals(ProjectNextActionType.WILL_RUN_ERRAND)) {
      description = "<i>" + i_ + " will run errand to</i> " + getNextDescription();
    } else if (type.equals(ProjectNextActionType.GOAL)) {
      if (nextProjectContact == null) {
        description = "<i>" + i_have + " set a goal to </i> " + getNextDescription();
      } else {
        description = "<i>" + i_have + " set a goal with " + nextProjectContact.getName()
            + " to</i> " + getNextDescription();
      }
    } else if (type.equals(ProjectNextActionType.TASK)) {
      if (nextProjectContact == null) {
        description = "<i>" + i_have + " set a task to </i> " + getNextDescription();
      } else {
        description = "<i>" + i_have + " set a task with " + nextProjectContact.getName()
            + " to</i> " + getNextDescription();
      }
    } else if (type.equals(ProjectNextActionType.MIGHT)) {
      description = "<i>" + i_ + " might</i> " + getNextDescription();
    } else if (type.equals(ProjectNextActionType.COMMITTED_TO)) {
      if (nextProjectContact == null) {
        description = "<i>" + i_have + " committed to </i> " + getNextDescription();
      } else {
        description = "<i>" + i_have + " committed to " + nextProjectContact.getName() + " to</i> "
            + getNextDescription();
      }
    } else if (type.equals(ProjectNextActionType.OVERDUE_TO)) {
      if (nextProjectContact == null) {
        description = "<i>" + i_am + " overdue to</i> " + getNextDescription();
      } else {
        description = "<i>" + i_am + "overdue in committment to " + nextProjectContact.getName()
            + " to</i> " + getNextDescription();
      }
    } else if (type.equals(ProjectNextActionType.WAITING)) {
      if (nextProjectContact == null) {
        description = "<i>" + i_am + "waiting for </i> " + getNextDescription();
      } else {
        description = "<i>" + i_am + "waiting for " + nextProjectContact.getName() + " to</i> "
            + getNextDescription();
      }
    }
    return description;
  }

  public void setNextDescription(String nextDescription) {
    this.nextDescription = nextDescription;
  }

  public Date getNextDue() {
    return this.nextDue;
  }

  public void setNextDue(Date nextDue) {
    this.nextDue = nextDue;
  }

  public String getNextActionType() {
    return this.nextActionType;
  }

  public void setNextActionType(String nextActionType) {
    this.nextActionType = nextActionType;
  }

  public Integer getNextTimeEstimate() {
    return this.nextTimeEstimate;
  }

  public String getNextTimeEstimateMinsForDisplay() {
    if (nextTimeEstimate == null) {
      return "";
    }
    return "" + nextTimeEstimate;
  }

  public String getNextTimeEstimateForDisplay() {
    if (nextTimeEstimate == null) {
      return "";
    }
    return getTimeForDisplay(getNextTimeEstimate());
  }

  public static String getTimeForDisplay(int nextTimeEstimateTotal) {
    String time = "";
    if (nextTimeEstimateTotal < 10) {
      time = "0:0" + nextTimeEstimateTotal;
    } else if (nextTimeEstimateTotal < 60) {
      time = "0:" + nextTimeEstimateTotal;
    } else {
      int hour = nextTimeEstimateTotal / 60;
      int minute = nextTimeEstimateTotal % 60;
      if (minute < 10) {
        time = hour + ":0" + minute;
      } else {
        time = hour + ":" + minute;
      }
    }
    return time;
  }

  public void setNextTimeEstimate(Integer nextTimeEstimate) {
    this.nextTimeEstimate = nextTimeEstimate;
  }

  public Integer getNextContactId() {
    return this.nextContactId;
  }

  public void setNextContactId(Integer nextContactId) {
    this.nextContactId = nextContactId;
  }

  public Integer getNextActionId() {
    return this.nextActionId;
  }

  public void setNextActionId(Integer nextActionId) {
    this.nextActionId = nextActionId;
  }

  public ProjectProvider getProvider() {
    return provider;
  }

  public void setProvider(ProjectProvider provider) {
    this.provider = provider;
  }

  public Date getNextDeadline() {
    return nextDeadline;
  }

  public void setNextDeadline(Date nextDeadline) {
    this.nextDeadline = nextDeadline;
  }

  public String getTaskStatus() {
    return taskStatus;
  }

  public void setTaskStatus(String taskStatus) {
    this.taskStatus = taskStatus;
  }

  public int getGoalActionId() {
    return goalActionId;
  }

  public void setGoalActionId(int goalActionId) {
    this.goalActionId = goalActionId;
  }
}
