package org.openimmunizationsoftware.pt.model;

import org.openimmunizationsoftware.pt.report.definition.ReportDefinition;
import org.openimmunizationsoftware.pt.report.definition.ReportDefinitionPro;
import org.openimmunizationsoftware.pt.report.definition.ReportDefinitionXML;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * ReportProfile generated by hbm2java
 */
public class ReportProfile implements java.io.Serializable {

  public static final String ENABLED = "E";
  public static final String DISABLED = "D";

  public static final String PROFILE_TYPE_XML_DEFINED = "XML";
  public static final String PROFILE_TYPE_PROGRES_REPORT = "PRO";

  private int profileId;
  private Integer extendsProfileId;
  private String profileLabel;
  private String providerId;
  private String username;
  private String userId;
  private String profileType;
  private String useStatus;
  private String extendStatus;
  private String contextType;
  private String selectorType;
  private byte[] definition;
  private ReportSchedule reportSchedule = null;
  private String reportCSS;

  public String getReportCSS() {
    return reportCSS;
  }

  public void setReportCSS(String reportCSS) {
    this.reportCSS = reportCSS;
  }

  public ReportSchedule getReportSchedule() {
    return reportSchedule;
  }

  public void setReportSchedule(ReportSchedule reportSchedule) {
    this.reportSchedule = reportSchedule;
  }

  public ReportProfile() {}

  public ReportProfile(int profileId) {
    this.profileId = profileId;
  }

  public String getUserId() {
    return userId;
  }

  public void setUserId(String userid) {
    this.userId = userid;
  }

  public ReportProfile(int profileId, Integer extendsProfileId, String profileLabel,
      String providerId, String username, String profileType, String useStatus, String extendStatus,
      String contextType, String selectorType, byte[] definition) {
    this.profileId = profileId;
    this.extendsProfileId = extendsProfileId;
    this.profileLabel = profileLabel;
    this.providerId = providerId;
    this.username = username;
    this.profileType = profileType;
    this.useStatus = useStatus;
    this.extendStatus = extendStatus;
    this.contextType = contextType;
    this.selectorType = selectorType;
    this.definition = definition;
  }

  public boolean isExtendable() {
    return ENABLED.equals(extendStatus);
  }

  public int getProfileId() {
    return this.profileId;
  }

  public void setProfileId(int profileId) {
    this.profileId = profileId;
  }

  public Integer getExtendsProfileId() {
    return this.extendsProfileId;
  }

  public void setExtendsProfileId(Integer extendsProfileId) {
    this.extendsProfileId = extendsProfileId;
  }

  public String getProfileLabel() {
    return this.profileLabel;
  }

  public void setProfileLabel(String profileLabel) {
    this.profileLabel = profileLabel;
  }

  public String getProviderId() {
    return this.providerId;
  }

  public void setProviderId(String providerId) {
    this.providerId = providerId;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public String getProfileType() {
    return this.profileType;
  }

  public void setProfileType(String profileType) {
    this.profileType = profileType;
  }

  public String getUseStatus() {
    return this.useStatus;
  }

  public boolean isEnabled() {
    return ENABLED.equals(useStatus);
  }

  public void setUseStatus(String useStatus) {
    this.useStatus = useStatus;
  }

  public String getExtendStatus() {
    return this.extendStatus;
  }

  public void setExtendStatus(String extendStatus) {
    this.extendStatus = extendStatus;
  }

  public String getContextType() {
    return this.contextType;
  }

  public void setContextType(String contextType) {
    this.contextType = contextType;
  }

  public String getSelectorType() {
    return this.selectorType;
  }

  public void setSelectorType(String selectorType) {
    this.selectorType = selectorType;
  }

  public byte[] getDefinition() {
    return this.definition;
  }

  public void setDefinition(byte[] definition) {
    this.definition = definition;
  }

  ReportDefinition reportDefinition = null;

  public void clearReportDefinition() {
    reportDefinition = null;
  }

  public ReportDefinition getReportDefinition() {
    if (reportDefinition == null) {
      if (PROFILE_TYPE_XML_DEFINED.equals(profileType)) {
        reportDefinition = new ReportDefinitionXML(this);
      } else if (PROFILE_TYPE_PROGRES_REPORT.equals(profileType)) {
        reportDefinition = new ReportDefinitionPro(this);
      }
    }
    return reportDefinition;
  }


  public String getReportText() {
    return getReportDefinition().getReportText();
  }


}
