package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * Sequence generated by hbm2java
 */
public class Sequence implements java.io.Serializable {

  private String tableName;
  private int sequenceId;

  public Sequence() {}

  public Sequence(String tableName, int sequenceId) {
    this.tableName = tableName;
    this.sequenceId = sequenceId;
  }

  public String getTableName() {
    return this.tableName;
  }

  public void setTableName(String tableName) {
    this.tableName = tableName;
  }

  public int getSequenceId() {
    return this.sequenceId;
  }

  public void setSequenceId(int sequenceId) {
    this.sequenceId = sequenceId;
  }

}
