package org.openimmunizationsoftware.pt.model;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * TrackerKeysId generated by hbm2java
 */
public class TrackerKeysId implements java.io.Serializable {

  private static final long serialVersionUID = -8556875942982415045L;

  private String keyName;
  private int keyType;
  private String keyId;

  public TrackerKeysId() {}

  public TrackerKeysId(String keyName, int keyType, String keyId) {
    this.keyName = keyName;
    this.keyType = keyType;
    this.keyId = keyId;
  }

  public String getKeyName() {
    return this.keyName;
  }

  public void setKeyName(String keyName) {
    this.keyName = keyName;
  }

  public int getKeyType() {
    return this.keyType;
  }

  public void setKeyType(int keyType) {
    this.keyType = keyType;
  }

  public String getKeyId() {
    return this.keyId;
  }

  public void setKeyId(String keyId) {
    this.keyId = keyId;
  }

  public boolean equals(Object other) {
    if ((this == other))
      return true;
    if ((other == null))
      return false;
    if (!(other instanceof TrackerKeysId))
      return false;
    TrackerKeysId castOther = (TrackerKeysId) other;

    return ((this.getKeyName() == castOther.getKeyName()) || (this.getKeyName() != null
        && castOther.getKeyName() != null && this.getKeyName().equals(castOther.getKeyName())))
        && (this.getKeyType() == castOther.getKeyType())
        && ((this.getKeyId() == castOther.getKeyId()) || (this.getKeyId() != null
            && castOther.getKeyId() != null && this.getKeyId().equals(castOther.getKeyId())));
  }

  public int hashCode() {
    int result = 17;

    result = 37 * result + (getKeyName() == null ? 0 : this.getKeyName().hashCode());
    result = 37 * result + this.getKeyType();
    result = 37 * result + (getKeyId() == null ? 0 : this.getKeyId().hashCode());
    return result;
  }

}
