package org.openimmunizationsoftware.pt.model;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * WebUser generated by hbm2java
 */
@SuppressWarnings("serial")
public class WebUser implements java.io.Serializable {

  public static final String USER_TYPE_ADMIN = "admin";
  public static final String USER_TYPE_USER = "user";

  public static final String AMERICA_DENVER = "America/Denver";

  private String username;
  private int contactId;
  private String password;
  private ProjectProvider provider = null;
  private boolean trackTime = false;
  private boolean manageBudget = false;
  private String userType;
  private WebUser parentWebUser = null;
  private TimeZone timeZone = TimeZone.getTimeZone(WebUser.AMERICA_DENVER);

  public Calendar getCalendar() {
    Calendar calendar = Calendar.getInstance(timeZone);
    return calendar;
  }

  public SimpleDateFormat getDateFormat(String s) {
    SimpleDateFormat sdf = new SimpleDateFormat(s);
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public SimpleDateFormat getTimeFormat() {
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy hh:mm aaa");
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public SimpleDateFormat getDateFormat() {
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public SimpleDateFormat getMonthFormat() {
    SimpleDateFormat sdf = new SimpleDateFormat("MMMM yyyy");
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public WebUser getParentWebUser() {
    return parentWebUser;
  }

  public void setParentWebUser(WebUser parentWebUser) {
    this.parentWebUser = parentWebUser;
  }

  public boolean isManageBudget() {
    return manageBudget;
  }

  public void setManageBudget(boolean manageBudget) {
    this.manageBudget = manageBudget;
  }

  public boolean isUserTypeAdmin() {
    return USER_TYPE_ADMIN.equals(userType);
  }

  public String getUserType() {
    return userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }

  public boolean isTrackTime() {
    return trackTime;
  }

  public void setTrackTime(boolean trackTime) {
    this.trackTime = trackTime;
  }

  private ProjectContact projectContact = null;

  public ProjectContact getProjectContact() {
    return projectContact;
  }

  public void setProjectContact(ProjectContact projectContact) {
    this.projectContact = projectContact;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public int getContactId() {
    return this.contactId;
  }

  public void setContactId(int contactId) {
    this.contactId = contactId;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone;
  }

  public ProjectProvider getProvider() {
    return provider;
  }

  public void setProvider(ProjectProvider provider) {
    this.provider = provider;
  }

  // make a function that is given a date, that may be null, and if not returns if
  // the date is today
  public boolean isToday(Date d) {
    if (d == null) {
      return false;
    }
    Calendar c = getCalendar();
    return sameDay(c, d);
  }

  public boolean sameDay(Calendar c1, Date d) {
    if (d == null) {
      return false;
    }
    Calendar c2 = getCalendar();
    c2.setTime(d);
    boolean s = sameDay(c1, c2);
    return s;
  }

  public static boolean sameDay(Calendar c1, Calendar c2) {
    return c1.get(Calendar.MONTH) == c2.get(Calendar.MONTH)
        && c1.get(Calendar.DAY_OF_MONTH) == c2.get(Calendar.DAY_OF_MONTH)
        && c1.get(Calendar.YEAR) == c2.get(Calendar.YEAR);
  }

}
