package org.openimmunizationsoftware.pt.model;

import java.text.SimpleDateFormat;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZoneId;
import java.util.Calendar;
import java.util.Date;
import java.util.TimeZone;

// Generated Dec 12, 2012 3:50:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * WebUser generated by hbm2java
 *
 * <p>
 * Date/time usage guidelines:
 * <ul>
 * <li>Use this class as the single source for "now" and "today" in user-facing
 * logic.</li>
 * <li>Do not use system-default clock/time-zone calls (for example,
 * Calendar.getInstance(),
 * LocalDate.now(), LocalDateTime.now(), or ZoneId.systemDefault()) when logic
 * should follow
 * the signed-in user's time zone.</li>
 * <li>For display formatting, use getDateFormat(...), getDateFormat(),
 * getTimeFormat(), and
 * getMonthFormat().</li>
 * <li>For date math and comparisons tied to user-local day boundaries, use
 * helpers such as
 * now(), getLocalDateToday(), startOfDay(...), endOfDay(...), and
 * isSameDay(...).</li>
 * </ul>
 */
public class WebUser implements java.io.Serializable {

  public static final String USER_TYPE_ADMIN = "admin";
  public static final String USER_TYPE_USER = "user";

  public static final String AMERICA_DENVER = "America/Denver";

  private String username;
  private int contactId;
  private String password;
  private ProjectProvider provider = null;
  private boolean trackTime = false;
  private String userType;
  private WebUser parentWebUser = null;
  private TimeZone timeZone = TimeZone.getTimeZone(WebUser.AMERICA_DENVER);

  public Calendar getCalendar() {
    Calendar calendar = Calendar.getInstance(timeZone);
    return calendar;
  }

  public Calendar getCalendar(Date date) {
    Calendar calendar = getCalendar();
    if (date != null) {
      calendar.setTime(date);
    }
    return calendar;
  }

  public Date now() {
    return new Date();
  }

  public long nowMillis() {
    return System.currentTimeMillis();
  }

  public ZoneId getZoneId() {
    return timeZone.toZoneId();
  }

  public LocalDateTime getLocalDateTimeNow() {
    return LocalDateTime.ofInstant(Instant.ofEpochMilli(nowMillis()), getZoneId());
  }

  public LocalDate getLocalDateToday() {
    return getLocalDateTimeNow().toLocalDate();
  }

  public Date toDate(LocalDate localDate) {
    if (localDate == null) {
      return null;
    }
    return Date.from(localDate.atStartOfDay(getZoneId()).toInstant());
  }

  public Date toDate(LocalDateTime localDateTime) {
    if (localDateTime == null) {
      return null;
    }
    return Date.from(localDateTime.atZone(getZoneId()).toInstant());
  }

  public Date toDateAtCurrentTime(LocalDate localDate) {
    if (localDate == null) {
      return null;
    }
    LocalDateTime localDateTime = LocalDateTime.of(localDate, getLocalDateTimeNow().toLocalTime());
    return toDate(localDateTime);
  }

  public LocalDate toLocalDate(Date date) {
    if (date == null) {
      return null;
    }
    return date.toInstant().atZone(getZoneId()).toLocalDate();
  }

  public LocalDateTime toLocalDateTime(Date date) {
    if (date == null) {
      return null;
    }
    return date.toInstant().atZone(getZoneId()).toLocalDateTime();
  }

  public Date startOfDay(Date date) {
    if (date == null) {
      return null;
    }
    Calendar calendar = getCalendar(date);
    calendar.set(Calendar.HOUR_OF_DAY, 0);
    calendar.set(Calendar.MINUTE, 0);
    calendar.set(Calendar.SECOND, 0);
    calendar.set(Calendar.MILLISECOND, 0);
    return calendar.getTime();
  }

  public Date endOfDay(Date date) {
    if (date == null) {
      return null;
    }
    Calendar calendar = getCalendar(date);
    calendar.set(Calendar.HOUR_OF_DAY, 23);
    calendar.set(Calendar.MINUTE, 59);
    calendar.set(Calendar.SECOND, 59);
    calendar.set(Calendar.MILLISECOND, 999);
    return calendar.getTime();
  }

  public Date getToday() {
    return startOfDay(now());
  }

  public Date getTomorrow() {
    return addDays(getToday(), 1);
  }

  public Date addDays(Date date, int days) {
    if (date == null) {
      return null;
    }
    Calendar calendar = getCalendar(date);
    calendar.add(Calendar.DAY_OF_MONTH, days);
    return calendar.getTime();
  }

  public SimpleDateFormat getDateFormat(String s) {
    SimpleDateFormat sdf = new SimpleDateFormat(s);
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public SimpleDateFormat getTimeFormat() {
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy hh:mm aaa");
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public SimpleDateFormat getDateFormat() {
    SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public SimpleDateFormat getMonthFormat() {
    SimpleDateFormat sdf = new SimpleDateFormat("MMMM yyyy");
    sdf.setTimeZone(timeZone);
    return sdf;
  }

  public Date parseDate(String dateString) {
    Date date = null;
    if (dateString != null && dateString.length() > 0) {
      SimpleDateFormat sdf1 = this.getDateFormat("MM/dd/yyyy");
      try {
        date = sdf1.parse(dateString);
      } catch (Exception e) {
        // Try again with fresh SimpleDateFormat
        sdf1 = this.getDateFormat("MM/dd/yyyy");
        try {
          date = sdf1.parse(dateString);
        } catch (Exception e2) {
          // Unable to parse date, return null
          // (calling code is responsible for error handling)
        }
      }
    }
    return date;
  }

  public WebUser getParentWebUser() {
    return parentWebUser;
  }

  public void setParentWebUser(WebUser parentWebUser) {
    this.parentWebUser = parentWebUser;
  }

  public boolean isUserTypeAdmin() {
    return USER_TYPE_ADMIN.equals(userType);
  }

  public String getUserType() {
    return userType;
  }

  public void setUserType(String userType) {
    this.userType = userType;
  }

  public boolean isTrackTime() {
    return trackTime;
  }

  public void setTrackTime(boolean trackTime) {
    this.trackTime = trackTime;
  }

  private ProjectContact projectContact = null;

  public ProjectContact getProjectContact() {
    return projectContact;
  }

  public void setProjectContact(ProjectContact projectContact) {
    this.projectContact = projectContact;
  }

  public String getUsername() {
    return this.username;
  }

  public void setUsername(String username) {
    this.username = username;
  }

  public int getContactId() {
    return this.contactId;
  }

  public void setContactId(int contactId) {
    this.contactId = contactId;
  }

  public String getPassword() {
    return this.password;
  }

  public void setPassword(String password) {
    this.password = password;
  }

  public TimeZone getTimeZone() {
    return timeZone;
  }

  public void setTimeZone(TimeZone timeZone) {
    this.timeZone = timeZone == null ? TimeZone.getTimeZone(WebUser.AMERICA_DENVER) : timeZone;
  }

  public ProjectProvider getProvider() {
    return provider;
  }

  public void setProvider(ProjectProvider provider) {
    this.provider = provider;
  }

  // make a function that is given a date, that may be null, and if not returns if
  // the date is today
  public boolean isToday(Date d) {
    if (d == null) {
      return false;
    }
    Calendar c = getCalendar();
    return sameDay(c, d);
  }

  public boolean sameDay(Calendar c1, Date d) {
    if (d == null) {
      return false;
    }
    Calendar c2 = getCalendar();
    c2.setTime(d);
    boolean s = sameDay(c1, c2);
    return s;
  }

  public boolean isSameDay(Date d1, Date d2) {
    if (d1 == null || d2 == null) {
      return false;
    }
    return toLocalDate(d1).equals(toLocalDate(d2));
  }

  public static boolean sameDay(Calendar c1, Calendar c2) {
    return c1.get(Calendar.MONTH) == c2.get(Calendar.MONTH)
        && c1.get(Calendar.DAY_OF_MONTH) == c2.get(Calendar.DAY_OF_MONTH)
        && c1.get(Calendar.YEAR) == c2.get(Calendar.YEAR);
  }

}
